Add support for add_prefix
jobready/codeclimate-test-reporter-buildkite-plugin pull request #14
Opened 2022-12-13 20:08 UTC by curtiscook

Adds a parameter to allow control of `--add-prefix` in Buildkite

2022-12-14 00:07 UTC, s01ipsist requested changes
Seems reasonable to add this option as a matching option that has existed on the format-coverage command since v0.3.0
https://github.com/codeclimate/test-reporter/blob/master/CHANGELOG.md#v030-2017-10-02

2022-12-14 00:22 UTC, s01ipsist commented
LGTM. Will look to publish a new package soon

2022-12-14 00:22 UTC, merged

2022-12-14 01:39 UTC, s01ipsist commented
Hey @curtiscook .
I've realised, albeit too late, that this line
```
add_prefix=${BUILDKITE_PLUGIN_CODECLIMATE_TEST_REPORTER_ADD_PREFIX:-""}
```
is redundant as the `$add_prefix` var isn't used anywhere. I've removed in the release tidy up commit.
https://github.com/jobready/codeclimate-test-reporter-buildkite-plugin/pull/15

2023-01-13 08:45 UTC, louman commented
@s01ipsist @curtiscook currently using v2.1 and trying to upgrade to the latest version of the plugin and while the docs say `prefix` is optional, I get this warning:

```
/var/lib/buildkite-agent/plugins/github-com-jobready-codeclimate-test-reporter-buildkite-plugin-v2-3/hooks/command: line 25: BUILDKITE_PLUGIN_CODECLIMATE_TEST_REPORTER_ADD_PREFIX: unbound variable
```

And finally the error:

```
Error: expected 24 parts, received 1 parts
```

I'm not sure yet if the error is related to the absence of a prefix (still debugging) but it seems the changes made recently are not backwards compatible so we should probably state that in the changelog.

2023-01-13 22:38 UTC, curtiscook commented
This its probably defaulting to undefined instead of emptystring. Can you try setting prefix to emptystring? should be a quick way to find out

2023-01-13 23:32 UTC, louman commented
> This its probably defaulting to undefined instead of emptystring. Can you try setting prefix to emptystring? should be a quick way to find out

I added a random prefix and that confirmed that the issue was indeed the lack of a prefix.

2023-01-14 01:18 UTC, curtiscook commented
Ok thats good. The default prefix is an emptystring, so that could be a workaround. The pr should be small but i need to be around a computer to write and submit

2023-01-14 01:51 UTC, s01ipsist commented
Happy to bake that fix into https://github.com/jobready/codeclimate-test-reporter-buildkite-plugin/pull/16/files 
Good test coverage would have prevented this regression!

2023-01-14 06:58 UTC, curtiscook commented
> Happy to bake that fix into https://github.com/jobready/codeclimate-test-reporter-buildkite-plugin/pull/16/files Good test coverage would have prevented this regression!

I think this will fix it: https://github.com/jobready/codeclimate-test-reporter-buildkite-plugin/pull/17